homepage/messages/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, TextAreaField
from wtforms.validators import DataRequired, ValidationError
from homepage.models import User, Message

def generate_user_list():
        return [(user.username, user.username) for user in User.query.all()]
    

class NewMessageForm(FlaskForm):
    recipient = SelectField("Send To:", choices=[], validators=[DataRequired()])
    subject = StringField("Subject", validators=[DataRequired()])
    body = TextAreaField("Body", validators=[DataRequired()])
    submit = SubmitField("Send Message")
    
    

homepage/notes/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class NewNoteForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    content = TextAreaField("Note Here", validators=[DataRequired()])
    submit = SubmitField("Save Note")

homepage/messages/routes.py
from flask import Blueprint
from datetime import datetime
from flask import Flask, Response, render_template, url_for, redirect, flash, request, abort
from flask_login import login_user, current_user, logout_user, login_required
from flask_mail import Message as ExternalMessage
from homepage import db
from homepage.messages.forms import NewMessageForm
from homepage.models import User, Note, Link, Message

messages = Blueprint('messages', __name__)

# I think I don't need this anymore, but not 100% sure
"""def coerce_recipient_username(recipient_data):
    x = recipient_data.split("'")
    return x[1]"""

@login_required
@messages.route('/view_messages')
def view_messages():
    message_list = []
    user = User.query.order_by(Message.time_sent.desc()).get(current_user.id)
    sent_messages = user.sent_messages
    for message in sent_messages:
        sender = current_user.username
        recipient = User.query.get(message.recipient_id).username
        message_list.append((message, sender, recipient))
    for message in Message.query.order_by(Message.time_sent.desc()).filter_by(recipient_id=current_user.id):
        message.unread = False
        db.session.commit()
        sender = User.query.get(message.sender_id).username
        recipient = current_user.username
        message_list.append((message, sender, recipient))

    sorted_message_list = sorted(
        message_list,
        key=lambda x: datetime.strptime(x[0].time_sent.strftime('%m/%d/%Y/%H'), '%m/%d/%Y/%H'), reverse=True
    )
    return render_template('view_messages.html', messages=sorted_message_list)

@messages.route('/new_message', methods=['GET', 'POST'])
@login_required
def new_message():
    possible_recipients = [(user.username, user.username) for user in User.query.all()]
    form = NewMessageForm(choices=possible_recipients)
    form.recipient.choices = possible_recipients
    if form.validate_on_submit():
        recipient_username = form.recipient.data
        recipient_id_number = User.query.filter_by(username=recipient_username).first().id
        message = Message(sender_id=current_user.id, subject=form.subject.data, 
                            body=form.body.data, sender=current_user, recipient_id=recipient_id_number)
        db.session.add(message)
        db.session.commit()
        return redirect(url_for("main.home"))
    return render_template("new_message.html", title="New Message", form=form, possible_recipients=possible_recipients)

@login_required
@messages.route('/messages/<int:message_id>/')
def view_message(message_id):
    message = Message.query.get_or_404(message_id)
    if current_user.id != message.recipient_id and current_user.id != message.sender_id:
        abort(403)
    sender = User.query.get(message.sender_id).username
    recipient = User.query.get(message.recipient_id).username

    return render_template('message.html', message=message, sender=sender, recipient=recipient)

homepage/notes/routes.py
from flask import Blueprint
from flask import Flask, Response, render_template, url_for, redirect, flash, request, abort
from flask_login import login_user, current_user, logout_user, login_required
from homepage import db
from homepage.notes.forms import NewNoteForm
from homepage.models import User, Note

notes = Blueprint('notes', __name__)

@notes.route('/new_note', methods=['GET', 'POST'])
@login_required
def new_note():
    form = NewNoteForm()
    if form.validate_on_submit():
        note = Note(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(note)
        db.session.commit()
        return redirect(url_for("main.home"))
    return render_template("new_note.html", title="New Note", form=form)

@login_required
@notes.route('/notes')
def view_notes():
    return(render_template('notes.html', notes=current_user.notes))

@login_required
@notes.route("/notes/<int:note_id>", methods=['GET', 'POST'])
def edit_note(note_id):
    note = Note.query.get_or_404(note_id)
    if current_user.id != note.user_id:
        abort(403)
    form = NewNoteForm()
    if form.validate_on_submit():
        note.content = form.content.data
        note.title = form.title.data
        db.session.commit()
        flash("Your Note has been Updated", "success")
        return redirect(url_for('notes.view_notes'))
    elif request.method == 'GET':
        form.title.data = note.title
        form.content.data = note.content
    return render_template('edit_note.html', title=note.title, note=note, form=form)

@login_required
@notes.route('/notes/<int:note_id>/delete', methods=['POST'])
def delete_note(note_id):
    note = Note.query.get_or_404(note_id)
    if current_user.id != note.user_id:
        abort(403)
    db.session.delete(note)
    db.session.commit()
    flash('Your Note has been deleted!', 'info')
    return redirect(url_for('main.home'))


homepage/users/routes.py
from flask import Blueprint
import os
from flask import Flask, Response, render_template, url_for, redirect, flash, request, abort
from flask_login import login_user, current_user, logout_user, login_required
from flask_mail import Message as ExternalMessage
from homepage import db, bcrypt,  mail
from homepage.users.forms import (RegistrationForm, LoginForm, LinkForm, DeleteLinkForm, 
                                ChangeWeatherForm, RequestResetForm, ResetPasswordForm)
from homepage.models import User, Link, Message
from homepage.users.utils import get_json_data, generate_quote, check_address

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    quote_tuple = generate_quote(os.getcwd() + "/homepage/static/quotes.json")
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, 
                    password=hashed_password, zip_code=form.zip_code.data)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created - you can now log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title="Register", form=form, quote_tuple=quote_tuple)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    quote_tuple = generate_quote(os.getcwd() + "/homepage/static/quotes.json")
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('main.home'))
        else:
            flash('Login Failed. Check password/email!', 'danger')
    return render_template('login.html', title="Login", form=form, quote_tuple=quote_tuple)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    link_form = LinkForm()
    weather_form = ChangeWeatherForm()
    quote_tuple = generate_quote(os.getcwd() + "/homepage/static/quotes.json")
    # Link Form Validation
    if link_form.validate_on_submit():
        link = Link(title=link_form.name.data, address=link_form.address.data, user_id=current_user.id)
        if check_address(link_form.address.data) == "VALID":
            db.session.add(link)
            db.session.commit()
            flash("Link Added", 'success')
            return redirect(url_for('users.account'))
        else:
            flash("Invalid URL - try again. Make sure to add \"https://\"", "danger")
        return redirect(url_for('users.account'))
    
    # Change Weather Form Validation
    elif weather_form.validate_on_submit():
        zip_code = str(weather_form.zip_code.data)
        current_user.zip_code = zip_code
        db.session.commit()
        flash("Zip Code Updated", 'success')
        return redirect(url_for('users.account'))

    return render_template('account.html', title="Account", quote_tuple=quote_tuple, link_form=link_form, weather_form=weather_form)



def send_reset_email(user):
    token = user.get_reset_token()
    msg = ExternalMessage('Password Reset Request',
                sender='ngerrard.pythondevelopment@gmail.com', \
                recipients=[user.email])
    msg.body = f"""To reset your password, visit the following link:
{url_for('users.reset_token', token=token, _external=True)}

If you did not make this request, then simply ignore this email, and no changes will be made to your account.
This link will expire 15 minutes after the request is made.
"""
    mail.send(msg)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    quote_tuple = generate_quote(os.getcwd() + "/homepage/static/quotes.json")

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instruction to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', quote_tuple=quote_tuple, title='Reset Passwrod', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    quote_tuple = generate_quote(os.getcwd() + "/homepage/static/quotes.json")

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been successfully reset.', 'success')
        return redirect(url_for('users.login'))

    return render_template("reset_token.html", quote_tuple=quote_tuple, title="Reset Password", form=form)

@users.route('/account/link<int:link_id>/delete', methods=['POST'])
@login_required
def remove_link(link_id):
    link = Link.query.get_or_404(link_id)
    if link.author != current_user:
        abort(403)
    db.session.delete(link)
    db.session.commit()
    flash("Link Deleted", 'success')
    return redirect(url_for('account'))

homepage/templates/about.html
{% extends "new_layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-8">
            <h1>About this Site</h1>
            <p> 
                HomePage v. 0.2.0<br><br>
                Updates:<br>
                - Added messaging feature<br>
                - Removed inaccurate time greeting<br>
                - Updated site infrastructure for scalability and security<br>
                - Improved notes functionality, for editing and removing<br>
                - Added front end password reset with emailed tokens, although unfortunately the current service I user for a server won't allow access on port 25, so it doesnt actually work. You still have to reach out to me to get a password reset token.<br>
                - Changed accounts to require a (mostly) valid emailed<br><br>
                
                Roadmap for Version 0.2.1:<br>
                - Add news apis for WSJ, LAT, WashPost<br>
                - Improve messaging speed, organization, and security<br>
                - Add data to weather queries, and improve graphic styling<br>
                <br>
                As always, I am open to input, so please feel free to message me (in the website now :P) with any thoughts or insights or criticism.
            </p>
        </div>
        <div class="col-sm-4">
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">{{ quote_tuple[1] }}</h5>
                    <p class="card-text">{{ quote_tuple[0] }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
             Need an Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
        </small>
    </div>
    
</div>
   
{% endblock content %}

homepage/templates/edit_note.html
{% extends "new_layout.html" %}
{% block content %}
    <div class="container">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <row class="">
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                        {% if form.title.errors %}
                            {{ form.title(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.title(class="form-control form-control-lg") }}
                        {% endif %}
                </div>
            </row>
            <row class="">
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                        {% if form.content.errors %}
                            {{ form.content(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class="form-control form-control-lg") }}
                        {% endif %}
                </div>
            </row>
            <row>
                {{ form.submit(class="btn bg-dark text-light")}}
                 <!-- Button trigger modal -->
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModalCenter">
                    Delete Note
                </button>
            </row>
        </form>
        <!-- Modal -->
        <div class="modal fade" id="deleteModalCenter" tabindex="-1" role="dialog" aria-labelledby="deleteModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLongTitle">Delete Note</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                Are you sure you want to delete this note?
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <form action="{{ url_for('notes.delete_note', note_id=note.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
                </div>
            </div>
            </div>
        </div>
    </div>
 {% endblock content %}

homepage/templates/home.html
{% extends "new_layout.html" %}
{% block content %}
    <div class="jumbotron text-center align-self-center bg-light text-dark">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="card" class="align-center">
                        <div class="card-header">
                            <h1 class="text-dark">Weather in {{ current_user.zip_code }}</h1>
                        </div>
                        <div class="card-body">
                            <p class="m-0">Temperature: {{ weatherdata["temp"] }}&#176; F</p>
                            <p class="m-0">Feels Like: {{ weatherdata["feels_like"] }}&#176; F</p>
                            <p class="m-0">High: {{ weatherdata["temp_max"] }}&#176; F</p>
                            <p class="m-0">Low: {{ weatherdata["temp_min"] }}&#176; F</p>
                            <p class="m-0">Conditions: {{ weatherdata["description"] }}</p>
                        </div>
                        
                    </div>
                </div>
                <div class="col-md-4 align-center">
                    {% for link in links %}
                    <a href="{{ link.address }}" target=_blank class="btn btn-lg btn-secondary text-light m-1">{{ link.title }}</a>
                    {% endfor %}
                    <a href="{{ url_for('users.account') }}" target=_blank class="btn btn-lg btn-info text-light m-1">Add Links?</a>

                    <!-- {% for favicon in favicons %}
                    <a href="{{ favicon }}">
                        <img src="/static/users/nick/fb32.png">
                    </a>
                    {% endfor %} -->
                </div>
            </div>
        </div>        
    </div>
    <div class="container pb-4">
        <div class="row">
            <div class="col-sm-6">
                <h2 class="text-dark text-center">From the New York Times:</h2>
                <ul class="list-group border border-light">
                    {% for story in trending_stories %}
                    <li class="list-group-item text-dark bg-light border-light p-1"><a href="{{ story['url'] }}" target=_blank class="btn btn-md btn-block btn-secondary text-light">{{ story['title'] }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-sm-6">
                <h2 class="text-dark text-center">Notes:</h2>
                {% for note in notes %}
                    <div class="card mt-3">
                        <div class="card-body">
                            <h5 class="card-title">{{ note.title }}</h5>
                            <p class="card-text">{{ note.content }}</p>
                            <a href="{{ url_for('notes.edit_note', note_id=note.id) }}" class="card-link">View/Edit Note</a>
                        </div>
                    </div>
                {% endfor %}
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="{{ url_for('notes.new_note') }}" class="btn btn-lg btn-secondary text-light mt-3 btn-block">New Note</a>
                        </div>
                        <div class="col-sm-6">
                            <a href="{{ url_for('notes.view_notes') }}" class="btn btn-lg btn-secondary text-light mt-3 btn-block">View Notes</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
 {% endblock content %}

homepage/templates/login.html
{% extends "new_layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-8">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Login</legend>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn bg-dark text-light")}}
                </div>
                <small class="text-muted ml-2">
                    <a href="{{  url_for('users.reset_request')  }}">Forgot Password?</a>
                </small>
            </form>
        </div>
        <div class="col-sm-4">
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">{{ quote_tuple[1] }}</h5>
                    <p class="card-text">{{ quote_tuple[0] }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
             Need an Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
        </small>
    </div>
    
</div>
   
{% endblock content %}

homepage/templates/message.html
{% extends "new_layout.html" %}
{% block content %}
<h2 class="text-dark text-center">Message:</h2>
<div class="container pb-4">
    <div class="card mt-3">
        <div class="card-body">
            <h5 class="card-title"><strong>Subject:    </strong>{{ message.subject }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Sent by: {{ sender }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Received by: {{ recipient }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Time Sent: {{ message.time_sent.strftime('%Y-%m-%d %H:%M') }} UTC</h6>
            <p class="card-text"><strong>Body:    </strong>{{ message.body }}</p>
            <a href="{{ url_for('messages.new_message') }}" class="btn btn-secondary">Reply</a>

        </div>
    </div>
</div>

    
 {% endblock content %}

homepage/templates/new_message.html
{% extends "new_layout.html" %}
{% block content %}
    <div class="container">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <row class="">
                <div class="form-group">
                    <!-- {{ form.recipient.label(class="form-control-label") }}
                    {{ form.recipient(class="form-control form-control-lg") }} -->
                    {{ form.recipient.label(class="form-control-label") }}
                        {% if form.recipient.errors %}
                            {{ form.recipient(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.recipient.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.recipient(class="form-control form-control-lg") }}
                        {% endif %}
                </div>
            </row>
            <row class="">
                <div class="form-group">
                    {{ form.subject.label(class="form-control-label") }}
                        {% if form.subject.errors %}
                            {{ form.subject(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.subject.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.subject(class="form-control form-control-lg") }}
                        {% endif %}
                </div>
            </row>
            <row class="">
                <div class="form-group">
                    {{ form.body.label(class="form-control-label") }}
                        {% if form.body.errors %}
                            {{ form.body(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.body.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.body(class="form-control form-control-lg") }}
                        {% endif %}
                </div>
            </row>
            <row>
                {{ form.submit(class="btn bg-dark text-light")}}
            </row>
        </form>
    </div>
 {% endblock content %}

homepage/templates/new_note.html
{% extends "new_layout.html" %}
{% block content %}
    <div class="container">
        <h1 class="text-center">New Note:</h1>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <row class="">
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                        {% if form.title.errors %}
                            {{ form.title(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.title(class="form-control form-control-lg") }}
                        {% endif %}
                </div>
            </row>
            <row class="">
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                        {% if form.content.errors %}
                            {{ form.content(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class="form-control form-control-lg") }}
                        {% endif %}
                </div>
            </row>
            <row>
                {{ form.submit(class="btn bg-dark text-light")}}
            </row>
        </form>
    </div>
 {% endblock content %}

homepage/templates/notes.html
{% extends "new_layout.html" %}
{% block content %}
<h2 class="text-dark text-center">Notes:</h2>
<div class="container pb-4">
    {% for note in notes %}
    <div class="card mt-3">
        <div class="card-body">
            <h5 class="card-title">{{ note.title }}</h5>
            <p class="card-text">{{ note.content }}</p>
            <a href="{{ url_for('notes.edit_note', note_id=note.id) }}" class="card-link">View/Edit Note</a>

        </div>
    </div>
{% endfor %}
<div class="containter">
    <div class="row justify-content-center">
        <div class="col-sm-4">
            <a href="{{ url_for('notes.new_note') }}" class="btn btn-lg btn-secondary text-light mt-3 btn-block">New Note</a>
        </div>
    </div>
</div>
</div>

    
 {% endblock content %}

homepage/templates/view_messages.html
{% extends "new_layout.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-dark text-center align-center">Your Messages</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            {% for message in messages %}
            <div class="card text-center">
                <div class="card-body block">
                <h5 class="card-title">{{ message[0].subject }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">Time Sent: {{ message[0].time_sent.strftime('%Y-%m-%d %H:%M') }} UTC</h6>
                <h6 class="card-subtitle mb-2 text-muted">Sender: {{ message[1] }}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Recipient: {{ message[2] }}</h6>
                <p class="card-text">{{ message[0].content }}</p>
                <a href="{{ url_for('messages.view_message', message_id=message[0].id) }}" class="btn btn-secondary">View</a>
                <a href="{{ url_for('messages.new_message') }}" class="btn btn-secondary">Reply</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="row pt-3">
        <a href="{{ url_for('messages.new_message') }}" class="btn btn-secondary">Send New Message</a>
    </div>
</div>

    
 {% endblock content %}